### PR TITLE
Game history in profile file

### PR DESCRIPTION
**Pull request by MinsuKin**
스크린샷 2023-10-14 오후 4 29 55

### CODE REVIEW

**Comment by josiaskas** [comment]
@MinsuKin is it ready ?

**Comment by MinsuKin** [comment]
are we going to save score for AI BOT?
or we will just leave it like this?

**Comment by MinsuKin** [comment]
스크린샷 2023-10-21 오후 4 18 31

**Comment by josiaskas** [comment]
> are we going to save score for AI BOT?
> 
> or we will just leave it like this?

I have merge the first one, I love the idea of full score or achievements in the top I will merge your last commit also. For bot we can add another action type for it, since the score is deeply linked with a user in the database. And we will update if the other members want it

**Comment by MinsuKin** [comment]
If you merge the last commit, you can close this merge request, or just let me know.

I think it makes sense for me to add AI BOT's score in the history view too.

Since all 3 of us are in the school, I asked them and they agreed too :)

**Pull request merged**
